import { ai_icon } from "../../assets/icons/pricinngs-icons/pricing-iconst";
import { woo_icon } from "../../assets/icons/pricinngs-icons/pricing-iconst";
const pricingData = [
  {
    price: "Free",
    text: "Easy Start for Beginners to Explore Galleries",
    advantages: [
      "Unlimited Galleries",
      "Unlimited Users",
      "9 Gallery Views",
      "Live Demo",
      "Gutenberg Block Support",
      "Elementor Widget Integration",
      "Divi Builder Compatibility",
      "WPBakery Page Builder Available",
      "10+ Pre-built Templates",
    ],
    id: 1,
    title: "Starter",
    href: "https://wordpress.org/plugins/regallery/",
  },
  {
    price: "$29.9",
    text: "For Photographers & Professionals, Needing Creative Galleries",
    advantages: [
      "Unlimited Galleries",
      "Unlimited Users",
      "9 Gallery Views",
      "Live Demo",
      "Gutenberg Block Support",
      "Elementor Widget Integration",
      "Divi Builder Compatibility",
      "WPBakery Page Builder Available",
      "30+ Pre-built Templates",
      "Use on 1 Site",
      "Pro Templates",
      <>Generated Image Title{ai_icon}</>,
      <>Generated Image Description{ai_icon}</>,
      <>Generated Image Alt Text{ai_icon}</>,
      <>WooCommerce Products{woo_icon}</>,
      "1 Year Pro Support",
    ],
    id: 2,
    duration: "1 year",
    title: "Basic",
    href: "https://regallery.team/checkout/?plan=basic",
  },

  {
    price: "$49.9",

    text: "For Businesses & Agencies, Needing Custom Galleries",
    advantages: [
      "Unlimited Galleries",
      "Unlimited Users",
      "9 Gallery Views",
      "Live Demo",
      "Gutenberg Block Support",
      "Elementor Widget Integration",
      "Divi Builder Compatibility",
      "WPBakery Page Builder Available",
      "30+ Pre-built Templates",
      "Use on 5 Sites",
      "Pro Templates",
      <>Generated Image Title{ai_icon}</>,
      <>Generated Image Description{ai_icon}</>,
      <>Generated Image Alt Text{ai_icon}</>,
      <>WooCommerce Products{woo_icon}</>,
      "1 Year Pro Support",
      "1 Year Customizations",
    ],
    id: 3,
    duration: "1 Year",
    title: "Plus",
    href: "https://regallery.team/checkout/?plan=plus",
  },
];

export default pricingData;
